### ISSUE TITLE
Converting JSON to EDI X12

### ISSUE THREAD

**Issue by djorgji** [jf-tech/omniparser#183] opened 2022-11-15 20:41 UTC
Hi all, first of all I would say this tool is great, thanks for all that you have done. I just have a simple question if there is a way to convert json to EDI (X12), or whether something like that is on a roadmap somewhere?

**Comment by jf-tech** [comment] 2022-11-16 07:32
Omniparser is by current design a parser - it ingests data and transforms into json. It doesn't have any writer functionalities nor does it support transforming json into other format.

That said I'm very interested in your use case and want to see, if possible for your to share, a few examples to understand what capabilities it requires if such features were to be added.

**Comment by djorgji** [comment] 2022-11-16 14:37
Yep, I guess our need is more of a transformer. The use case has both EDI inbound, but also outbound EDI. Data inbound in EDI that is transformed to JSON so it can be loaded it to a NoSQL DB. After some processing we need to transform the changed data back to EDI, and integrate it out.

**Comment by jf-tech** [comment] 2022-11-17 20:57
Omniparser is schema driven when transforming data into json, during which vast majority (in fact all) of our use cases extract small amount of data from original EDI and write into resulting json.

So you can see the process "filters" down info,  versus your proposed output process, a ton of EDI segs have to written out to make it a valid EDI doc. 

While theoretically we can still make it schema driving for the output process, the schema would be really dense I suspect. 

I don't have a good idea how to approach this request yet. Any suggestions welcome. The key principles to hold:
- esse of use (in terms of schema writing and non-coding requirements)
- extensibility / pluggability (so not EDI only solution)

**Comment by jf-tech** [comment] 2022-11-27 23:25
@djorgji any comments/ideas? I will close the ticket soon if no new addition coming.

**Comment by jf-tech** [comment] 2022-11-29 02:07
Closed due to lack of activities and no agreed action items on the feature request.

**Comment by aKardasz** [comment] 2022-12-08 20:13
One way might be to do a json structure that can be traversed to export a edi file.

For example Translate EDI to JSON, then json to EDI,

So it would end up looking like this json to EDI:

{
"ISA": {  "Element1" : "", "element2": "" etc} So key is the segement identifier, and then subnest that segments other data etc. I can go a little further into this, but maybe looking at the guides provided by stedi.com/ and its json configs might help to build out such a functionality.

**Comment by jf-tech** [comment] 2023-01-05 23:47
@djorgji @aKardasz Sorry for the delayed follow-up. It is not about what the mechanism to use for the json->EDI transform - there are plenty of ways/tricks to enable such transform. What I'm looking for is a complete/real-world scenario to study the use case so we can decide whether the json->EDI (or for that matter, json-><any format>) transform belongs to this library and if so how to design it correctly. Check back my previous comment (https://github.com/jf-tech/omniparser/issues/183#issuecomment-1319191996) for my questions/concerns.

I'm a bit inclined to close this ticket given I'm not receiving feedbacks from the original ticket issuer, but let's wait for a few more days.

**Comment by djorgji** [comment] 2023-01-07 17:39
Hi sorry, with year end/holidays I have been out of hand.

The use case is essentially a two way ETL between 2 incompatible systems. Most modern tooling uses JSON, so converting from archaic formats like EDI into JSON for processing or storing (example writing to a NoSQL db), and then on the way "back" needing to send it in w.e. format the older system requires. Like the commenter above mentioned stedi seems to do that (first time I hear of them), however after a quick review of their capabilities based on their website/docs, I can't possibly use it since it is API based, adds delays when dealing with multiple transactions.

We are a startup in transportation, where a lot of trading partners have very old systems, that utilize EDI/SOAP/CSV. For example most carrier status updates come via an ` EDI 214 Transportation Carrier Shipment Status`, and we could receive batches with multiple lines. On the flip side `EDI 204 Motor Carrier Load Tender` is sent to let the carrier know you have a load for them to pickup, again it can be batched if in the timeframe between cron job runs more than one load became available for that carrier.

We have SFTP folders setup for Inbound (ex: 214) where we need to go from EDI to JSON, and Outbound (ex: 204) where we need to go from JSON to EDI, while calling our restful API.

Funny you should mention other formats, couple of weeks ago we got a use case converting json to xml (SOAP), we used omniparser to do json to json transform, and then marshal go objects into xml, on the way back we used omniparser to go from XML to JSON. 

You have created a great tool, thank you! I actually checked with the team if any of them wanted to help, but no one felt comfortable with that saldy, I guess they are a shy bunch, personally I am an older Java guy sadly.  Let me know if we can help any further.

**Comment by jf-tech** [comment] 2023-01-07 21:14
@djorgji thanks a lot for your support! if you're doing this on behalf of your company, please send me an email at jf.tech.llc@gmail.com so I can send your a [company license](https://github.com/jf-tech/omniparser/blob/master/sponsors/COMPANY_LICENSE.md).

And thanks for the project background. What I meant early by "real world scenario" is that I need to take a look:
- sample input EDI, needs to be complete not excerpts,
- how much info you're extract from it and convert into what json format, aka sending me your omniparser schema,
- then tell me what the complete output EDI would look like.

The reason is (like I [mentioned before](https://github.com/jf-tech/omniparser/issues/183#issuecomment-1319191996): in practically all our use cases we only extract very small subset info from input EDI and filter out the rest. In such case, reconstructing a similar output EDI from the small subset of data is nearly impossible. Thus I'm curiously how your use case (with actual samples) looks like. Are you extract all info/fields out from the incoming EDI, transform into json, and then possibly unmarshal to golang objects, then looking for some way to marshal it out into out-going EDI?

Your use case of `JSON<->XML (SOAP)`, that's interesting. Basically you use golang's builtiin `encoding/xml` to marshal objects into XML. That's what I was thinking along that line - omniparser from the beginning was designed as an *ingester*, it was not designed to be an omni-writer. Once omniparser ingests (and transforms) various data formats into the standard golang fav JSON, you can simply unmarshal it into golang objects. From there, you can marshal your objects into json or XML supported by builtin `encoding` package. What we lack here is maybe a tag based marshaler for EDI? Don't know for sure, need to see your example.

**Comment by jf-tech** [comment] 2023-01-08 00:21
A follow-up note: omniparser tries to be domain agnostic - it intends to be general purpose ingester/transformer for all formats into JSON. Seems like what you're interested in is some library of pre-made EDI specific schemas (like 214, 210, 240, 805, etc) and some accompanying output schemas/specs to write the ingested JSONs into output EDIs, pretty much like what stedi.com is doing. If that's the case, I would argue these pre-made schemas don't belong to omniparser, but rather a omniparser related schema library. However, we do need to either create inside omniparser or create a new library to handle the JSON to output format writing aspect of the request.

**Comment by jf-tech** [comment] 2023-01-08 08:13
Once again, a sample input EDI, a sample omniparser schema, and a sample output EDI would be really helpful

**Comment by djorgji** [comment] 2023-01-08 19:18
I am working on anonymizing some of the samples, and I will send you a couple of samples over the next couple of days to your email.

Keeping the parser agnostic to the specific X12 or EDIFACT, makes sense. We do sometimes support custom schemas, so an agnostic library would be best.

I am not sure the parser needs to worry about the completeness of the EDI output that would be up to the users not run into a "garbage in garbage out" type of situation. For example on the XML example we had to add SOAP envelope element before marshaling.

**Comment by jf-tech** [comment] 2023-03-08 15:38
Closed due to lack of activities.

**Comment by tb-artomu** [comment] 2023-04-10 01:43
Converting JSON to EDI X12. Is this supported? Is there any example？

**Comment by jf-tech** [comment] 2023-04-10 02:36
@tb-artomu no omniparser is a  general purpose  parser for data ingestion. It doesn't have output capabilities no such capabilities are on roadmap. That said, @djorgji and I are discussing the possibility of creating a separate library to support schema driven writer features. It's at very very initial stage and obviously no milestones and ETA yet.

**Comment by lg-RahulYadav** [comment] 2023-04-19 09:34
Hello @jf-tech, I also do have same requirement as @djorgji. Let me know if I can be of any help. Also, if you are aware of any such solution/library I can use for the time being?

**Comment by jf-tech** [comment] 2023-04-28 21:09
@lg-RahulYadav @djorgji I'm wondering what's the best collaborative way to make progress on this issue. Slack/discord seems bit too early for such a small project (omniparser). Wondering if we should simply start an email thread talking about requirements, intended inputs and outputs. I have sketched some initial and very very rough ideas how to do output, most likely outside omniparser, but under the same umbrella of text based input/output parsing and transformation. The trouble I have is that we in the past had no requirements doing output, thus the imaginary input->transform->output pipeline isn't very solid in my imagination, and thus hard to come up with concrete solution. What we need is actual use cases, then we can analyze how to design this.

@lg-RahulYadav,
> aware of any such solution/library I can use for the time being

No, not that I'm aware of. Always check awesome-go first.

**Comment by jf-tech** [comment] 2023-04-28 21:30
Some offline discussion notes for creating such an schema based output library:

> I'm wondering how we should deal with generic requirements of writing to a structured flat file (csv, potentially XML, EDI, etc) which contains loops, hierarchies, etc.
>
> Also wondering about the verbosity issue of such writing schema: imagine there is an input EDI, you want to do some processing about it (say standardize all the date/time fields, or do some currency conversion), and write out under another EDI spec. One way of doing it is to parse and suck in *EVERY* segment, element, and component data (:O, OMG!), store in an intermediate format, such as JSON, then output schema will have to specify yet again, *EVERY* segment, element, and component in the target output EDI file. I can imagine for any nontrivial EDI spec, such input schema (for omniparser) and output schema (for this new library we're discussing about) would be incredibly verbose and hard to maintain.
>
> The verbosity issue is one of the reasons I'm struggling to come up with an elegant solution. The majority of our past use cases of omniparser is to *distill* information, i.e. extract a relatively small number of the important fields out of an otherwise large input. So essentially it's a compression algorithm, which makes the omniparser schema light and maintainable.
>
> I'm wondering if something like this would be the future direction: creating a generic writing library based on some schema, which supports, flat, loop, and hierarchy. Then create format specific libraries on top of the core writing library. Such format specific libraries can include, say EDI specific format, in which we can create EDI specific input (yes, we need omniparser input schema as well) and matching output schema. These schemas will be dense, long, and very industry and use-case specific and maintained by each company I imagine.

**Comment by lg-RahulYadav** [comment] 2023-04-29 11:07
For the time being, I tried implementing EDI to JSON, using templates. Because in real life case, companies choose a subset of segments for any particular format of EDI, So the solution I have been thinking of is, having file declarations same as of now we have in omniparser and fileoutput will be a template, atleast for EDI? 
Or 
As you mentioned we can have some intermediate json, and then convert that perticular json to other formats? for EDI specifically we can use templates? what are your thoughts on this?

**Comment by lg-RahulYadav** [comment] 2023-04-29 11:12
@tb-artomu You may explore the templates method. I recently was able to convert JSON to EDI x12 using python templates. ([MAKO](https://www.makotemplates.org/))

**Comment by djorgji** [comment] 2023-05-03 01:28
I would agree on the templates bit, from my understanding communicating with the EDI, there is a lot of variation between clients, and adoption of the "standard". either way there is a lot of "always output" parts.

**Comment by lg-RahulYadav** [comment] 2023-05-11 08:38
@djorgji true, I may be completing wrong here, So EDI follows a particular [structure](https://github.com/adamkasztenny/edi-schemas), taking X12 850 as an example, if we have input data filled in [mentioned structure](https://github.com/adamkasztenny/edi-schemas), then we can write it to X12 850 easily. If you have any idea how we can fill data in this particular format in case, we may choose other structures also?

**Comment by dhartford** [comment] 2023-07-26 17:39
In the context if 'reading a custom format' with omniparser (even if the current usecase is json), are there some examples of how to efficently 'hook' into the renderer/marshaller?

i.e. just thinking IDR, old school sax eventing, or if can 'aggregate' say EDI segment groups into smaller programmatic go structure (efficiently) to then send to a renderer/marshaller?

Old school smooks/java trying to shift to golang world, and this particular ticket is very interesting :-)

**Comment by alfredovaldes** [comment] 2024-07-15 16:06
Seeing as this issue is still open i'm throwing in my two cents:

At my workplace we have developed an EDI system that takes any kind of text file, extracts the information acording to an schema, checks business rules, validates and maps to any format, be it json, xml, edifact, x12, idoc, xlsx, etc...

This project contains over 1.7M lines of Go code, and the core packages are over 500K, so the feature discussed in this issue may be a severe undertaking.

Although i just discovered the project, I would be happy to contribute if there is renewed interest in tackling this issue, as i can see the potential to reduce the overall code base of our product using ominparser.

**Comment by jf-tech** [comment] 2024-08-04 03:04
Sorry, everyone involved here (@alfredovaldes @djorgji @dhartford @the-hotmann @aKardasz), for not updating this issue frequently. As we mentioned before, given we don't currently have a solid use case for such a template-driven JSON -> <various format> output `omniwriter` project, we're not moving forward with it. That is not saying we don't want to get involved, if concrete examples would be provided. By concrete, we mean real input, real output, and details about the mapping instructions, potentially multiple pairs, so we can analyze them and propose the best way of architecting such writer.

**Closed** 2024-10-15 00:07 UTC
